spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/motion-users
    username: postgres
    password: zxca
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8071

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    register-with-eureka: true
#  instance:
#    app-name: user-service
#    instance-id: ${spring.application.name}:${random.value}